### ISSUE TITLE
So outdated

### ISSUE THREAD

**Issue by BarbzYHOOL** [wowgame/client-data#1]
:) outdated and we'll soon upload new vmaps

**Comment by Yehonal** [comment]
Data is not retrieved by repository code but from release data.zip instead that you can find here:

https://github.com/wowgaming/client-data/releases

i've compiled vmap 3 times but we're changing them too often in AC. So please notify me any time you need new data and i'll re-extract and upload again.

**Comment by Yehonal** [comment]
You can notice the downloading function here:

https://github.com/azerothcore/azerothcore-wotlk/blob/879553ddf83085031641b19102e9cd97a3e334e8/apps/installer/includes/functions.sh#L205

it's downloading v5 that contains mmap 9, vmaps 4.2  , so it should be updated with latest AC. Isn't it?

**Comment by BarbzYHOOL** [comment]
Ok you probably updated them then :P
We changed recently and I thought you didn't, we are going to update to vmaps 4.3, I uploaded the data on megaupload on our PR https://github.com/azerothcore/azerothcore-wotlk/pull/1021

**Comment by BarbzYHOOL** [comment]
Note: on the releases page there is this written "updated mmaps from v6 to v8"

**Comment by BarbzYHOOL** [comment]
@Yehonal updated https://github.com/azerothcore/azerothcore-wotlk/commit/59d4e1d3a806a4f2f48f535be366bde1b24d737e

I have uploaded the files (but it's a contributor who extracted them and tested them) on mega https://mega.nz/#F!Am4DBKCR!o9Qj_xFLfsg4sczqg0xq2A

**Comment by Yehonal** [comment]
@BarbzYHOOL is that link still valid for latest AzerothCore? or do we have new maps now?

Moreover are they enus?

**Comment by BarbzYHOOL** [comment]
i don't know, check the discord and the wiki friend (compare latest links)!

and yes, they are enus
