### ISSUE TITLE
[Request] DBC for esES, esMX

### ISSUE THREAD

**Issue by solidmaxtor** [wowgame/client-data#2]
You could extract and have available the Spanish and Latin versions of the game client DBC

**Comment by Yehonal** [comment]
Sorry, could you explain better your issue?

NOTE: wowgaming organization doesn't have bounty system enabled and we won't enable it here

**Comment by solidmaxtor** [comment]
it is possible to extract and share the DBCs of the "esES" gameclient. reliable for current azeroth core, just like you have from enUS?

**Comment by Yehonal** [comment]
Sorry buy se can't offer such services because we don't have those clients.
The best way would be to extract just dbc using extractor tools that are
released by azerothcore. It's a process of few seconds.

Il Dom 18 Ago 2019, 11:34 Solid Maxtor <notifications@github.com> ha
scritto:

**Comment by Yehonal** [comment]
I close this issue, if you want to add DBCs from other languages you can always send a PR with the attached files and we can add them to our assets list
